### ISSUE TITLE
Tools Garantie aanpassing Sander

### ISSUE THREAD

**Issue by Fietsgoed** [elburgl69/fietsgoed-ws#9]
Hoi Leo,

Zou je de volgende punten kunnen veranderen in Garantie Tools.

1.	Claimresultaat

Dit wordt vaak direct ingevuld door de aanvrager, maar deze stap is volgens mij als je weet wat de daadwerkelijke claimresultaat is geworden. 

Misschien handig om dit meer onder aan te zetten met als kop tekst Claim verwerking / eind resultaat claim aanvraag.

2.	Historische overzicht

Deze pagina wordt wel erg lang en dit zorgt voor een langere laadtijd van deze pagina. 

Graag zouden we dit op volgorde van datum willen en dan van nieuw naar oud. 
Misschien is het dan handig om per pagina maximaal 30 aanvragen te zien en dat je dan doorheen kan bladeren. 

3.	Printen garantie claim

Bij de eerste aanvraag en je slaat deze op dan is het nu niet mogelijk om direct te printen. Dan moet je weer terug naar de betreffende claim om te laten printen. 

a.	Printen van document zelf.

Daarbij staat onderaan het document:
“Verwacht resultaat: Onbekend, standaard is crediteren.”

Zou je dit willen veranderen naar Verwacht resultaat: Onbekend (wat dan de status is van de betreffende claim) Volgende tekst mag dan worden weg gelaten. standaard is crediteren

4.	Nieuwe toevoeging

Na Claim Status graag keuze menu Gewenste afhandeling 
-	Nieuw onderdeel
-	Crediteren 

Het zou mooi zijn dat deze keuze dan ook terug te vinden is op de geprinte claim aanvraag.

**Comment by elburgl69** [comment]
Issues overgenomen in de omgeving van Tools. Sluit deze omdaty die voor de website (ws) niet relevant zijn.
